# Generated by Django 4.0.4 on 2023-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('dgs', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
